import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner'
import styles from '../styles/Home.module.css'

export default function Home() {
  const HadleOnBanerButtonHandler = event=>{
    console.log('Button Clicked')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CofeeShop Lookup
        </h1>

        <Banner buttonText="View Stores nearby" onButtonHandler={HadleOnBanerButtonHandler}/>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
