import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner'
import styles from '../styles/Home.module.css'

export default function Home() {
  const HadleOnBanerButtonHandler = event=>{
    console.log('Button Clicked')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffe Shop Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View Stores nearby" onButtonHandler={HadleOnBanerButtonHandler}/>
        <div className={styles.heroImage}>
          <Image src="/static/Header-Image.png" width={700} height={400} alt='The Header image'/>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
